# Get the python image
FROM python:latest

# Switch to app directory
WORKDIR /ts_adaptor

# Copy the requirements in to the app
COPY requirements.txt ./

# Install dependencies
RUN pip install -r requirements.txt

# Copy everything else
COPY . .

#Run the python script
ENTRYPOINT [ "python", "-u", "tsAdaptor.py" ]
