# Get the python image
FROM python:latest

# Switch to app directory
WORKDIR /front_end

# Copy the requirements in to the app
COPY requirements.txt ./

# Install dependencies
RUN pip install -r requirements.txt

# Copy everything else
COPY . .

#Run the python script
ENTRYPOINT [ "python", "front_end.py" ]

EXPOSE 8082