# Get the python image
FROM python:latest

# Switch to app directory
WORKDIR /Alert_service

# Copy the requirements in to the app
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything else
COPY . .

#Run the python script
ENTRYPOINT [ "python", "alert_service.py" ]

EXPOSE 83