# Get the python image
FROM python:latest

# Switch to app directory
WORKDIR /Catalog 
# si puo togliere

# Copy the requirements in to the app
COPY requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything else
COPY . .

#Run the python script
ENTRYPOINT [ "python", "-u", "catalog_manager.py" ]

EXPOSE 8081